apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: full-instrumentation
  namespace: monitoring
spec:
  exporter:
    endpoint: http://otlp-telemetry-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_always_on
  env:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_TRACES_EXPORTER
      value: otlp
