---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/version: "2.9.3"
  annotations:
spec:
  ports:
    - name: one
      port: 9092
    - name: two
      port: 9093
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/version: "2.9.3"
  annotations:
spec:
  ports:
    - name: one
      port: 9092
    - name: two
      port: 9093
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
