apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app: otel-collector
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
      prometheus/telemetry-app:
        config:
          scrape_configs:
            - job_name: 'quarkus-micrometer'
              metrics_path: '/q/metrics'
              scrape_interval: 3s
              static_configs:
                - targets: ['telemetry-app:8080']
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    exporters:
      prometheus:
        endpoint: "0.0.0.0:9090"
      otlp/tempo:
        endpoint: tempo-distributor-discovery:4317
        tls:
          insecure: true
    service:
      pipelines:
        metrics/1:
          receivers: [prometheus/telemetry-app]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/tempo]
