---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/version: "0.92.0"
data:
  relay: |
    extensions:
      health_check: {}

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      kubeletstats:
        collection_interval: 20s
        initial_delay: 1s
        auth_type: "serviceAccount"
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
        extra_metadata_labels:
        - container.id
        - k8s.volume.type
        k8s_api_config:
          auth_type: serviceAccount

    processors:
      batch:
        timeout: 200ms
      memory_limiter:
        check_interval: 5s
        limit_mib: 1500
        spike_limit_mib: 512

      k8sattributes:
        extract:
          labels:
          - tag_name: app.kubernetes.io.component
            key: app.kubernetes.io/component
            from: pod
          - tag_name: app.kubernetes.io.name
            key: app.kubernetes.io/name
            from: pod
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid

      attributes/loki-labels:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: app.kubernetes.io.name
      resource/loki-labels:
        attributes:
          - action: insert
            key: loki.resource.labels
            value: app.kubernetes.io.name, service.name, service.namespace, trace_id, span_id

      transform/add-trace-labels-to-attributes:
        error_mode: ignore
        log_statements:
        - context: log
          statements:
          - set(resource.attributes["trace_id"], trace_id.string)
          - set(resource.attributes["span_id"], span_id.string)
      transform/unify-app-name-label:
        error_mode: ignore
        trace_statements:
        - context: resource
          statements:
          - set(attributes["app.kubernetes.io/name"], attributes["app"])
          - delete_key(attributes, "app")
      transform/kubelet-metric-labels:
        error_mode: ignore
        metric_statements:
        - context: datapoint
          statements:
          - set(attributes["k8s.pod.name"], resource.attributes["k8s.pod.name"])
          - set(attributes["k8s.namespace.name"], resource.attributes["k8s.namespace.name"])
          - set(attributes["k8s.container.name"], resource.attributes["k8s.container.name"])
          - set(attributes["k8s.node.name"], resource.attributes["k8s.node.name"])

    exporters:
      debug:
        verbosity: detailed
      otlp/tempo:
        endpoint: tempo:4317
        tls:
          insecure: true
      otlphttp/prometheus:
        endpoint: http://prometheus:9090/api/v1/otlp
        tls:
          insecure: true
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
        tls:
          insecure: true

    connectors:
      servicegraph:

    service:
      extensions:
      - health_check
      pipelines:
        metrics/kubelets:
          receivers:
          - kubeletstats
          processors:
          - transform/kubelet-metric-labels
          exporters:
          - otlphttp/prometheus
          - debug
        metrics:
          receivers:
          - otlp
          processors:
          - memory_limiter
          - batch
          - k8sattributes
          - transform/unify-app-name-label
          exporters:
          - otlphttp/prometheus
        metrics/connector:
          receivers:
          - servicegraph
          processors:
          - memory_limiter
          - batch
          exporters:
          - otlphttp/prometheus
        traces:
          receivers:
          - otlp
          processors:
          - memory_limiter
          - batch
          - k8sattributes
          - transform/unify-app-name-label
          exporters:
          - otlp/tempo
          - servicegraph
        logs:
          receivers:
          - otlp
          processors:
          - memory_limiter
          - batch
          - k8sattributes
          - transform/unify-app-name-label
          - transform/add-trace-labels-to-attributes
          - attributes/loki-labels
          - resource/loki-labels
          exporters:
          - loki
