fullnameOverride: log-otel-collector
mode: daemonset
presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: false
  kubernetesAttributes:
    enabled: true
    # You can also configure the preset to add all of the associated pod's labels and annotations to you telemetry.
    # The label/annotation name will become the resource attribute's key.
    extractAllPodLabels: true
    extractAllPodAnnotations: true
config:
  extensions:
    basicauth/client:
      client_auth:
        username: admin
        password: admin
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp: null
  exporters:
    elasticsearch/log:
      endpoints: [http://elasticsearch-master:9200]
      logs_index: log_index
      sending_queue:
        enabled: true
        num_consumers: 20
        queue_size: 1000
    opensearch:
      http:
        endpoint: http://opensearch-cluster-master:9200
        auth:
          authenticator: basicauth/client
        tls:
          insecure: true
    debug:
      verbosity: detailed
  processors:
    transform/unify-app-name-label:
      error_mode: ignore
      trace_statements:
        - context: resource
          statements:
            - set(attributes["app.kubernetes.io/name"], attributes["app"])
            - delete_key(attributes, "app")
    memory_limiter:
      # 80% of maximum memory up to 2G
      limit_mib: 1500
      # 25% of limit up to 2G
      spike_limit_mib: 512
      check_interval: 5s
    batch:
      timeout: 200ms
  service:
    extensions: [basicauth/client]
    pipelines:
      logs:
        receivers: [filelog]
        processors: [memory_limiter, transform/unify-app-name-label]
        exporters: [debug,opensearch]
      metrics: null
      traces: null
ports:
  otlp-http:
    enabled: false
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  prometheus:
    enabled: false
