apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  selector:
    app: otel-collector
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
    - name: grpc-otlp
      protocol: TCP
      port: 4317
