apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-app
  namespace: monitoring
  labels:
    app.kubernetes.io/name: telemetry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telemetry-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telemetry-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: telemetry-app
          image: docker.collaud.me/telemetry-app:1.5.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_SERVICE_NAME
              value: telemetry-app
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.instance.id=$(POD_NAME),k8s.pod.uid=$(POD_UID)
            - name: OTEL_PYROSCOPE_START_PROFILING
              value: 'true'
            - name: PYROSCOPE_APPLICATION_NAME
              value: telemetry-app
            - name: PYROSCOPE_FORMAT
              value: jfr
            - name: PYROSCOPE_PROFILING_INTERVAL
              value: 10ms
            - name: PYROSCOPE_PROFILER_EVENT
              value: itimer
            - name: PYROSCOPE_PROFILER_LOCK
              value: 10ms
            - name: PYROSCOPE_PROFILER_ALLOC
              value: 512k
            - name: PYROSCOPE_UPLOAD_INTERVAL
              value: 15s
            - name: PYROSCOPE_LOG_LEVEL
              value: info
            - name: PYROSCOPE_SERVER_ADDRESS
              value: http://pyroscope:4040
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
