---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-overrides-config
  namespace: monitoring
  labels:
    helm.sh/chart: pyroscope-1.4.0
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/instance: pyroscope
    app.kubernetes.io/version: "1.3.0"
    app.kubernetes.io/managed-by: Helm
data:
  overrides.yaml: |
    overrides:
      {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-config
  namespace: monitoring
  labels:
    helm.sh/chart: pyroscope-1.4.0
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/instance: pyroscope
    app.kubernetes.io/version: "1.3.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    {}
