apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-app
  namespace: monitoring
  labels:
    app.kubernetes.io/name: telemetry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telemetry-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telemetry-app
    spec:
      containers:
        - name: telemetry-app
          image: stmichael/telemetry-app:1.2.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_SERVICE_NAME
              value: telemetry-app
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.instance.id=$(POD_NAME),k8s.pod.uid=$(POD_UID)
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
