---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-profiling
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: profiling
data:
  config.alloy: |-
    logging {
    	level  = "debug"
    	format = "logfmt"
    }

    discovery.kubernetes "local_pods" {
      selectors {
        field = "spec.nodeName=" + env("HOSTNAME")
        role = "pod"
      }
      role = "pod"
    }

    discovery.process "all" {
      join = discovery.kubernetes.local_pods.targets
    }

    discovery.relabel "java_pods" {
      targets = discovery.process.all.targets

      // Filter only java processes
      rule {
        source_labels = ["__meta_process_exe"]
        action = "keep"
        regex = ".*/java$"
      }
      rule {
        action = "keep"
        regex = "Running"
        source_labels = ["__meta_kubernetes_pod_phase"]
      }
      rule {
        action = "keep"
        source_labels = ["__meta_kubernetes_pod_annotation_monitoring_spoud_io_profiling"]
        regex = "true"
      }
      rule {
        action = "replace"
        source_labels = ["__meta_kubernetes_namespace"]
        target_label = "namespace"
      }
      rule {
        action = "replace"
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label = "pod"
      }
      rule {
        action = "replace"
        source_labels = ["__meta_kubernetes_pod_node_name"]
        target_label = "node"
      }
      rule {
        action = "replace"
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label = "container"
      }
      rule {
        action = "replace"
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label = "service_name"
      }
    }

    pyroscope.java "java" {
      forward_to = [pyroscope.write.example.receiver]
      targets = discovery.relabel.java_pods.output
    }

    pyroscope.write "example" {
      endpoint {
        url = "http://pyroscope:4040"
      }
    }
