{
 "title": "K8s",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory usage by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(k8s_node_name) (k8s_node_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_memory_usage_bytes{k8s_namespace_name!=\"kube-system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(k8s_node_name) (k8s_node_cpu_utilization_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(k8s_pod_name) (k8s_pod_cpu_utilization_ratio{k8s_namespace_name!=\"kube-system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem usage by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(k8s_node_name) (k8s_node_filesystem_usage_bytes / k8s_node_filesystem_available_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (k8s_pod_name) (k8s_pod_filesystem_usage_bytes{k8s_namespace_name!=\"kube-system\"} / k8s_pod_filesystem_available_bytes{k8s_namespace_name!=\"kube-system\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}