{
 "title": "Telemetry app",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Logs corresponding to traces",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"telemetry-app\", trace_id!=\"00000000000000000000000000000000\"}"
    }
   ]
  },
  {
   "title": "Hellos per name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (hello_counter_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "query": "{span.http.status_code>=200 && span.http.status_code<300}",
     "tableType": "traces"
    }
   ]
  }
 ]
}