apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
data:
  datasources.yml: |
    apiVersion: 1

    datasources:
      - name: Metrics
        type: prometheus
        access: proxy
        # Access mode - proxy (server in the UI) or direct (browser in the UI).
        url: http://prometheus:9090
        jsonData:
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          prometheusVersion: 2.44.0
          cacheLevel: 'High'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m
      - name: Traces
        type: tempo
        access: proxy
        # Access mode - proxy (server in the UI) or direct (browser in the UI).
        url: http://tempo:3100
      - name: Logs
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
