apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
data:
  datasources.yml: |
    apiVersion: 1

    datasources:
      - name: Metrics
        type: prometheus
        uid: metrics
        access: proxy
        # Access mode - proxy (server in the UI) or direct (browser in the UI).
        url: http://prometheus:9090
        jsonData:
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          prometheusVersion: 2.44.0
          cacheLevel: 'High'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m
      - name: Traces
        type: tempo
        uid: traces
        access: proxy
        # Access mode - proxy (server in the UI) or direct (browser in the UI).
        url: http://tempo:3100
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: metrics
      - name: Logs
        type: loki
        uid: logs
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
      - name: Profiles
        type: grafana-pyroscope-datasource
        uid: profiles
        url: http://pyroscope:4040
        jsonData:
          minStep: '15s'
  dashboards.yml: |
    apiVersion: 1

    providers:
    - name: 'test'
      type: file
      options:
        path: /etc/dashboards
        foldersFromFilesStructure: true
  app-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "loki",
            "uid": "PEA2100DC89AE9FE2"
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 3,
          "options": {
            "dedupStrategy": "none",
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": false,
            "showLabels": false,
            "showTime": false,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "pluginVersion": "10.3.1",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "PEA2100DC89AE9FE2"
              },
              "editorMode": "code",
              "expr": "{app_kubernetes_io_name=\"telemetry-app\", trace_id!=\"00000000000000000000000000000000\"}",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Logs corresponding to traces",
          "type": "logs"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "PA58DA793C7250F1B"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unitScale": true
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 4,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "PA58DA793C7250F1B"
              },
              "disableTextWrap": false,
              "editorMode": "code",
              "expr": "sum by (name) (hello_counter_total)",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "legendFormat": "__auto",
              "range": true,
              "refId": "A",
              "useBackend": false
            }
          ],
          "title": "Hellos per name",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "tempo",
            "uid": "P998741A58ED2B411"
          },
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unitScale": true
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "id": 2,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true
          },
          "pluginVersion": "10.3.3",
          "targets": [
            {
              "datasource": {
                "type": "tempo",
                "uid": "P998741A58ED2B411"
              },
              "key": "Q-eee02b0c-6e70-4b2f-acd9-2d23f9b9acf9-0",
              "limit": 20,
              "query": "{name=\"GET /hello/{name}\"}",
              "queryType": "traceql",
              "refId": "A",
              "tableType": "traces"
            }
          ],
          "title": "Successful requests",
          "transformations": [],
          "type": "table"
        },
        {
          "datasource": {
            "type": "grafana-pyroscope-datasource",
            "uid": "P535E52E4A2616EBE"
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          },
          "id": 5,
          "targets": [
            {
              "datasource": {
                "type": "grafana-pyroscope-datasource",
                "uid": "P535E52E4A2616EBE"
              },
              "groupBy": [],
              "labelSelector": "{service_name=\"random-generator\"}",
              "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds",
              "queryType": "profile",
              "refId": "A",
              "spanSelector": []
            }
          ],
          "title": "Panel Title",
          "type": "flamegraph"
        }
      ],
      "refresh": "",
      "schemaVersion": 39,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-3h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Telemetry app",
      "uid": "e9ccdb4b-5175-4c25-823f-e42893480619",
      "version": 1,
      "weekStart": ""
    }
