---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-kafka
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/version: "v1.0.0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-kafka
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/version: "v1.0.0"
rules:
  # Rules which allow discovery.kubernetes to function.
  - apiGroups:
      - ""
      - "discovery.k8s.io"
      - "networking.k8s.io"
    resources:
      - endpoints
      - endpointslices
      - ingresses
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-kafka
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/version: "v1.0.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-kafka
subjects:
  - kind: ServiceAccount
    name: alloy-kafka
    namespace: monitoring
