apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator
  namespace: monitoring
  labels:
    app.kubernetes.io/name: random-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: random-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: random-generator
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        monitoring.spoud.io/profiling: "true"
    spec:
      containers:
        - name: random-generator
          image: stmichael/random-generator:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: random-generator
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
