apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: monitoring
  labels:
    app.kubernetes.io/name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: consumer
      annotations:
        instrumentation.opentelemetry.io/inject-java: "full-instrumentation"
        monitoring.spoud.io/profiling: "true"
    spec:
      containers:
        - name: consumer
          image: stmichael/consumer:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MP_MESSAGING_INCOMING_HELLO_GROUP_ID
              value: consumer
            - name: OTEL_SERVICE_NAME
              value: consumer
            - name: OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED
              value: 'true'
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
