apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer2
  namespace: monitoring
  labels:
    app.kubernetes.io/name: consumer2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: consumer2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: consumer2
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: consumer2
          image: stmichael/consumer:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MP_MESSAGING_INCOMING_HELLO_GROUP_ID
              value: consumer2
            - name: OTEL_SERVICE_NAME
              value: consumer2
            - name: OTEL_PYROSCOPE_START_PROFILING
              value: 'true'
            - name: OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED
              value: 'true'
            - name: PYROSCOPE_APPLICATION_NAME
              value: consumer2
            - name: PYROSCOPE_FORMAT
              value: jfr
            - name: PYROSCOPE_PROFILING_INTERVAL
              value: 10ms
            - name: PYROSCOPE_PROFILER_EVENT
              value: itimer
            - name: PYROSCOPE_PROFILER_LOCK
              value: 10ms
            - name: PYROSCOPE_PROFILER_ALLOC
              value: 512k
            - name: PYROSCOPE_UPLOAD_INTERVAL
              value: 15s
            - name: PYROSCOPE_LOG_LEVEL
              value: info
            - name: PYROSCOPE_SERVER_ADDRESS
              value: http://pyroscope:4040
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
